# Generated by Django 5.1.1 on 2025-02-11 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0002_department_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='category',
            field=models.CharField(blank=True, choices=[('academic', 'Academic Departments'), ('arts', 'Arts & Creative Departments'), ('technical', 'Technical & Vocational Departments'), ('sports', 'Sports & Physical Education'), ('administrative', 'Administrative Departments')], max_length=20, null=True),
        ),
    ]
