# Generated by Django 5.1.5 on 2025-02-14 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="League",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Sport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "league",
                    models.CharField(
                        choices=[
                            ("champions_league", "Champions League"),
                            ("premier_league", "Premier League"),
                            ("final", "Final"),
                            ("friendly_game", "Friendly Game"),
                        ],
                        max_length=50,
                    ),
                ),
            ],
        ),
    ]
