# Generated by Django 5.1.5 on 2025-02-14 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Transport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "vehicle_type",
                    models.CharField(
                        choices=[
                            ("bus", "Bus"),
                            ("van", "Van"),
                            ("car", "Car"),
                            ("bike", "Bike"),
                        ],
                        max_length=20,
                    ),
                ),
                ("registration_number", models.CharField(max_length=20)),
                ("capacity", models.IntegerField(default=0)),
                ("description", models.TextField(blank=True)),
            ],
        ),
    ]
