# Generated by Django 5.1.1 on 2025-02-12 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
    ]
