# Generated by Django 5.1.1 on 2025-02-12 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_auto_20250212_1415'),
    ]

    operations = [
    ]
