# Generated by Django 5.1.5 on 2025-02-15 15:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teachers", "0003_auto_20250212_1430"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="teacher",
            name="date_joined",
        ),
        migrations.RemoveField(
            model_name="teacher",
            name="email",
        ),
        migrations.RemoveField(
            model_name="teacher",
            name="phone",
        ),
        migrations.RemoveField(
            model_name="teacher",
            name="profile_pic",
        ),
        migrations.AddField(
            model_name="teacher",
            name="profile_image",
            field=models.ImageField(blank=True, null=True, upload_to="teachers/"),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="department",
            field=models.CharField(
                choices=[
                    ("Computer Science", "Computer Science"),
                    ("Mathematics", "Mathematics"),
                    ("Physics", "Physics"),
                ],
                default="Computer Science",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
