# Generated by Django 5.1.1 on 2025-02-07 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0005_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='ownML1Dqf0C2vtQxzBu6Kp9ESgQSHR58', editable=False, max_length=32, unique=True),
        ),
    ]
