# Generated by Django 5.1.1 on 2025-02-07 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0008_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='5nwzW7oAN4oyFPstNkOlRMbmevSKSaEK', editable=False, max_length=32, unique=True),
        ),
    ]
