# Generated by Django 5.1.1 on 2025-02-11 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0012_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='IQXPE5mJQ3ofpaK3A8o3IXShWA7dTv3q', editable=False, max_length=32, unique=True),
        ),
    ]
