# Generated by Django 5.1.1 on 2025-02-12 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0013_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='JyPk70Cm8i2eH9XVLRnn4q6RuWXSA8SZ', editable=False, max_length=32, unique=True),
        ),
    ]
