# Generated by Django 5.1.1 on 2025-02-12 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0014_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='i7XBY5oT3aKXF9ieufWOxqJy917psWqS', editable=False, max_length=32, unique=True),
        ),
    ]
