# Generated by Django 5.1.1 on 2025-02-16 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0016_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='AcXflnVZ5L4wSxJmbKe1l7vn3AxIOuTb', editable=False, max_length=32, unique=True),
        ),
    ]
